# Setup
title:               Jon Powers
tagline:             'Development'
description:         'Powers Development'
url:                 https://powers.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jon Powers
  url:               https://powers.dev
  email:             jon@powers.dev

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
